# Generated by Django 4.2.16 on 2026-04-10 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True, null=True, upload_to="certificate_qr/"
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("is_emailed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
    ]
