# Generated by Django 4.2.16 on 2026-04-10 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0002_initial"),
        ("results", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="result",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="certificate",
                to="results.result",
            ),
        ),
    ]
